### ISSUE TITLE
MQTT message size limit

### ISSUE THREAD

**Issue by brainboutique** [johnboiles/esp-roomba-mqtt#7]
After charging, MQTT stopped working. Reason: https://github.com/knolleary/pubsubclient has documented limit to 128b - this is apparently exceeded when voltage and charge have sufficient digits.

Workaround: Prepend 
#define MQTT_MAX_PACKET_SIZE 256
before other includes or withing PubSubClient.h

**Comment by johnboiles** [comment]
If you build via platformio you should get this automatically because of [this line](https://github.com/johnboiles/esp-roomba-mqtt/blob/master/platformio.ini#L21) in the platformio.ini file

`build_flags = -DLOGGING=1 -DMQTT_MAX_PACKET_SIZE=512`

PubSubClient.h isn't included in this repo so I think it's out of the scope to have it modified here. Wouldn't be bad to mention this in the README though. Feel free to submit a modification to the README
